name: vibrate
description: A flutter plugin to vibrate the device
version: 0.0.2
author: Clovis Nicolas <clovisnicolas0@gmail.com>
homepage: https://github.com/clovisnicolas/flutter_vibrate

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: flutter.plugins.vibrate.vibrate
    pluginClass: VibratePlugin

