name: flutter_vibrate
description: A Haptic Feedback plugin.
version: 1.0.0
environment:
  sdk: ">=2.0.0 <3.0.0"
authors:
  - Clovis Nicolas <clovisnicolas0@gmail.com>
  - Rhodes Davis Jr. <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/flutter_vibrate

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: flutter.plugins.vibrate
    pluginClass: VibratePlugin

